# Site settings
title: Conan Mercer
description: Resume and Blog
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site e.g. http://yoursite.com

# User settings
username: Conan Mercer
user_description: <p> <b><span style="color:#9a4837;">I am a Chemistry Ph.D</span></b> now travelling the path of a <b><span style="color:#9a4837;">Data Engineer.</span></b> I apply fundamental scientific methods to solve technology problems in next generation businesses. Lately I have been immersed in <b><span style="color:#9a4837;">test engineering</span></b>, helping to build a great SaaS company at <a href="https://www.sage.com/en-gb/" target="_blank">Sage</a>, the world's largest supplier of enterprise resource planning software to small businesses.</b> I have over <b><span style="color:#9a4837;">5 year’s experience</span></b> in the management of international technology projects of a complex nature. I have strong technical abilities in Data Science that includes <b><span style="color:#9a4837;">Python programming</span></b>. During my Ph.D I acquired solid skills in <b><span style="color:#9a4837;">data science, public speaking and project management</span></b>. I have a proven ability to apply the latest research and techniques to solve a variety of scientific problems.
user_title: Data Engineer
email: conan.mercer1@gmail.com

# Google-analytics
google-analytics:
  id: "UA-148731075-1"

exclude: ["package.json", "src", "node_modules"]
