# Site settings
title: Conan Mercer
description: Resume and Blog
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site e.g. http://yoursite.com

# User settings
username: Conan Mercer
user_description: <p><b> I am a Chemistry Ph.D now travelling the path of a Computer Scientist. </b> I spend my free time working on Machine Learning projects. Lately I have been immersed in <b>test engineering</b> working for <a href="https://www.sage.com/en-gb/" target="_blank">Sage</a>, a Newcastle upon Tyne headquartered company that is the world's largest supplier of enterprise resource planning software to small businesses.</b></p> <p>I have over <b>5 year’s experience</b> in managing international projects with a complex nature. I have strong technical abilities in Data Science that includes <b>Python programming</b>. During my Ph.D I acquired solid skills in <b> data science, public speaking and project management</b>. I have a proven ability to apply the latest research and techniques to solve a variety of scientific problems.</p>
user_title: Applied Scientist
email: conan.mercer1@gmail.com

# Google-analytics
google-analytics:
  id: "UA-148731075-1"

exclude: ["package.json", "src", "node_modules"]
